apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-proxy
  labels:
    {{- include "jupyterhub.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "jupyterhub.matchLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "jupyterhub.matchLabels" . | nindent 8 }}
    spec:
      containers:
        - name: httpd-proxy
          image: {{ .Values.httpdProxy.image.name }}:{{ .Values.httpdProxy.image.tag }}
          ports:
            - containerPort: 80
            - containerPort: 443
