apiVersion: v1
kind: Service
metadata:
  name: httpd-proxy-public
  labels:
    {{- $_ := merge (dict "componentSuffix" "-public") . }}
    {{- include "jupyterhub.labels" $_ | nindent 4 }}
spec:
  selector:
    component: httpd-proxy
    release: {{ .Release.Name }}
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
    - name: https
      port: 443
      protocol: TCP
      targetPort: 443
  type: ClusterIP
