apiVersion: v1
kind: Service
metadata:
  name: httpd-proxy
  labels:
    {{- include "jupyterhub.labels" $_ | nindent 4 }}
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  - name: "443"
    port: 443
    targetPort: 443
  selector:
    component: httpd-proxy
