kind: ConfigMap
apiVersion: v1
metadata:
  name: shibboleth-sp-config
data:
  shibboleth2.xml: {{ .Values.shib.idp.shibboleth2-xml | b64enc }}
  idp-metadata.xml: {{ .Values.shib.idp.idp-metadata-xml | b64enc }}

