apiVersion: apps/v1
kind: Deployment
metadata:
  name: shib
  labels:
    {{- include "jupyterhub.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "jupyterhub.matchLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "jupyterhub.matchLabels" . | nindent 8 }}
    spec:
      name: shib
      restartPolicy: Always
      volumes:
        - name: sp-cert-key
          secret:
            secretName: sp-cert-key
      containers:
        - image: {{ .Values.shib.image.name }}:{{ .Values.shib.image.tag }}
          imagePullPolicy: Always
          name: sp
          volumeMounts:
            - name: sp-cert-key
              mountPath: "/run/secrets/sp-cert-key"
              readOnly: true
