apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: shib-sp
  labels:
    {{- include "jupyterhub.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "jupyterhub.matchLabels" . | nindent 6 }}
  volumes:
    - name: spkey
      secret:
        secretName: sp-key
  template:
    metadata:
      labels:
        {{- include "jupyterhub.matchLabels" . | nindent 8 }}
    spec:
      name: shib
      restartPolicy: Always
      containers:
        - image: {{ .Values.shib.image.name }}:{{ .Values.shib.image.tag }}
          imagePullPolicy: Always
          name: sp
          volumeMounts:
          - name: spkey
            mountPath: "/run/secrets/sp-key"
            readOnly: true
